module Stock
{
	// Requested stock does not exist.
	exception InvalidStockException {};
	
	struct StockQuote{
		long id;
		string name;
		double price;
	};
	
	
	interface CallbackHandler
	{
		//Oneway method called by quote server to deliver new quote
		oneway void push(in StockQuote data);
	};

	interface Notifying_Quoter
	{
		void register_callback_name(in string stockName, in CallbackHandler handler)
		raises (InvalidStockException);
		
		void unregister_callback_name(in string stockName, in CallbackHandler handler)
		raises (InvalidStockException);
	};
	
	interface Quoter {
	
		// Two-way operations to retrieve current stock value.
		StockQuote getQuoteByName (in string stockName) 
			raises (InvalidStockException);
			
		StockQuote getQuoteById (in long stockId) 
			raises (InvalidStockException);
	};
};
